name: Clippy

on: [push]

jobs:
  clippy_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install clippy
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features